### PR TITLE
Adding feature/new_oop branch.

### PR DESCRIPTION
**Pull request by ehkropf**
This should be the right branch. See previous pull request comments for details.

TLDR: start with the spec_*.m files to see package behaviour.

### CODE REVIEW

**Comment by tobydriscoll** [comment]
@ehkropf, Please push your branch first so that I can check it out and have a look.

**Comment by ehkropf** [comment]
Erm, did you give me push access to this repository? I did a fork, which should be public. Am I missing something?

**Comment by tobydriscoll** [comment]
No, I am. </blush>

---

Tobin Driscoll
Professor and Director of Graduate Studies
Department of Mathematical Sciences
University of Delaware,  Newark, DE 19716
Twitter: @tobydriscoll
https://twitter.com/intent/user?screen_name=tobydriscoll    Gplus:
+TobyDriscoll http://google.com/+TobyDriscoll

**Comment by tobydriscoll** [comment]
OK, now that I have it...can you point me to the highlights? Sorry I'm
being so clueless.

---

Tobin Driscoll
Professor and Director of Graduate Studies
Department of Mathematical Sciences
University of Delaware,  Newark, DE 19716
Twitter: @tobydriscoll
https://twitter.com/intent/user?screen_name=tobydriscoll    Gplus:
+TobyDriscoll http://google.com/+TobyDriscoll

**Comment by ehkropf** [comment]
No worries. And by "have it" I'm going to assume you've downloaded my fork. Such as it is.

So this stuff is at base what you had before which has been converted to the new "classdef" syntax, modulo some things I haven't got around to yet, of which I need to make a list. There are some changes to the way you were doing things. Most notably 'mobius' is now a subclass of 'conformalmap'. I'm currently using this branch as a base for what I'm working on at Imperial, so it's getting some application use.

Some operational examples are in the 'spec_*.m' files, that's probably the best place to start. I've made an attempt at the start of a "developer's guide" in the doc directory. I've also tried to setup unit testing (run from the 'run_test.m' function), but that code needs some serious love.

Obviously, feel free to pummel me with questions, comments or brutal criticism.

**Comment by ehkropf** [comment]
I also keep forgetting that not everyone, or maybe almost no one, sets their default figure background colour to white. So if the plots don't come out on your screen, that's probably why. Another thing for the list.

**Comment by tobydriscoll** [comment]
Great stuff, especially the Szego map.

You did use syntax on inputParser that only goes back to version 2013b. Something to think about as many people don't keep matlab up to date.

**Comment by ehkropf** [comment]
I was worried about that when I used inputParser. But then I thought I'd get things working, and do fixing later. Do you have any links that show matlab "backward compatibility brokenness" so to speak? I tried to find something like that for inputParser, but I couldn't come up with anything other than directly comparing version docs, which I clearly didn't do.

**Comment by tobydriscoll** [comment]
Pet peeve about matlab: they don't tell you when commands were introduced, altered, or deprecated. 

I think they changed 'addParamValue' to 'addParameter'. The old syntax seems to work still.

**Pull request merged**
